version: '3.4'

services:

  database:
    image: mysql
    container_name: mysqldb
    ports:
      - "3306:3306"
    expose: 
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_USER: registryuser
      MYSQL_PASSWORD: secretpassword
      MYSQL_DATABASE: animalregistry

  animalregistryapi:
    image: ${DOCKER_REGISTRY-}animalregistryapi
    build:
      context: .
      dockerfile: AnimalRegistryAPI/Dockerfile
    depends_on:
      - database
    ports:
      - "5000:80"
    restart: always
    environment:
      - MYSQL_DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Developement

volumes:
  db-volume: